### ISSUE TITLE
[BUG]: The introduction section is not designed properly and also the mobileview of that is not good can be changed.

### ISSUE THREAD

**Issue by mohit-bhandari45** [rbjks/rbjks.github.io#115] opened 2024-03-26 17:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Actually the introduction section of the website in home page is not looking good with inappropriate margins and padding.
Also the mobile view is looking very bad and it can broken with the column flex direction.

### Expected Behavior

The desktop view should be maintained with proper margin and padding.
The mobile view should also be improved with proper direction of the sections and the image and text should be one below other.

### Steps To Reproduce

1.Open the project
2.Preview the home page(index.html)
3.See the middle(introduction) section where there is image and text
4.See the middle(introduction) section in mobile view

### Anything else?

![image](https://github.com/rbjks/rbjks.github.io/assets/151373021/20fb8a0d-7d45-4909-a695-73413583d5c6)

**Comment by CampbellBrim** [comment] 2024-03-26 19:05
I would like to work on this.

**Comment by mohit-bhandari45** [comment] 2024-03-26 19:35
I have done coding part of this please assign me

**Comment by adityaraute** [comment] 2024-03-26 19:38
> I have done coding part of this please assign me

Sorry @mohit-bhandari45 ,
Since you didn't indicate that you wanted to work on this issue in your description, I assigned it to the first person requesting so. Now that it is already assigned to someone, it won't be appropriate for us to assign it to you as well.

We encourage all contributors to only start working on an issue after you are assigned to it.

**Comment by CampbellBrim** [comment] 2024-03-26 19:43
![Captura de tela 2024-03-26 164119](https://github.com/rbjks/rbjks.github.io/assets/84410954/5036ff73-aa41-4ce0-89cd-09b100a296b2)
I changed some of the margins and query rules. Does this look ok?

**Comment by adityaraute** [comment] 2024-03-26 19:46
- I'd prefer it if you could share a before/after set of screenshots. 
- I feel there is still some scope for improvement here with respect to text alignment.
- Also explore some other contrasting text colors instead of white and black

**Comment by CampbellBrim** [comment] 2024-03-26 19:49
Sounds great! I wasn't sure if I should mention text color.

**Comment by CampbellBrim** [comment] 2024-03-26 20:19
Before: 
![Captura de tela 2024-03-26 171751](https://github.com/rbjks/rbjks.github.io/assets/84410954/5972c92a-d3ef-4194-8766-cd99b00776f5)
After: 
![Captura de tela 2024-03-26 171719](https://github.com/rbjks/rbjks.github.io/assets/84410954/54711bca-670c-4727-aff6-ba51c5a07463)
Iphone 12 pro dimensions

**Comment by mohit-bhandari45** [comment] 2024-03-27 16:01
can i share my updates(ss) in this?

**Comment by adityaraute** [comment] 2024-04-04 11:32
> I am going to make small changes and post a pull request very soon.

@CampbellBrim Sure, waiting for your PR

> can i share my updates(ss) in this?

Feel free to share your comments @mohit-bhandari45 
But since the issue is assigned already, the assignee will be raising the PR

**Comment by CampbellBrim** [comment] 2024-04-04 13:52
I linked the PR to this issue. Does it look correct?

**Comment by agriyakhetarpal** [comment] 2024-04-04 14:13
I think the "Fixes" keyword should be directly before the issue number – I fixed it for you

**Comment by CampbellBrim** [comment] 2024-04-04 14:14
Thank you!

**Comment by mohit-bhandari45** [comment] 2024-04-04 15:19
please assign me
I can do it easily

**Comment by adityaraute** [comment] 2024-04-05 08:55
> please assign me I can do it easily

This issue has already been assigned to someone else. 
Please don't request assignment in such a case.

**Closed** 2024-04-11 10:07 UTC
