### ISSUE TITLE
Change font color.

### ISSUE THREAD

**Issue by ctrl07** [rbjks/rbjks.github.io#61] opened 2023-12-27 16:20 UTC
**Is your feature request related to a problem? Please describe.**
The Font color on the landing page is very light. I want to make it more readable by using a different color.

**Describe the solution you'd like**
I want to make it more readable by using a different color.

**Describe alternatives you've considered**
 Using the same font color through out the page.

**Comment by adityaraute** [comment] 2023-12-28 06:13
Hi @ctrl07 
Thanks for raising this issue. But this issue is a duplicate of #57 which has already been fixed.
However the font colour for the contact page is not correct. Perhaps you'd want to work on that?

**Comment by ctrl07** [comment] 2023-12-28 06:22
I am currently learning React. I am up for any task that will help me learn.

**Comment by adityaraute** [comment] 2023-12-28 06:28
Sadly, we aren't implementing React here. We just need to modify the text and underline color of navbar on the `contact` page of the website. This will be a CSS task.
If you're up for it, I can assign the task to you.

**Comment by ctrl07** [comment] 2023-12-28 06:34
Works for me :)

**Closed** 2023-12-28 06:35 UTC

**Comment by adityaraute** [comment] 2023-12-28 06:42
@ctrl07 I've created #63 for this. Please comment on there, so I can assign it to you.
